[package]
name = "zlib-sys"
version = "0.1.0"
authors = ["kaisawind <wind.kaisa@gmail.com>"]
edition = "2018"
links = "z"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
pkg-config = "0.3.17"